### ISSUE TITLE
2.0.9 版本的Creator  安装后报如下错误

### ISSUE THREAD

**Issue by zzjfengqing** [potato47/ccc-devtools#1]
Error: E:\devSoftWare\Creator209\CocosCreator\resources\static\preview-templates\index.jade:38
   36|     div#recompiling 
   37|       span Recompiling scripts, please wait for refresh... 
 > 38| include ./ccc-devtools/index.html 
   39|     script(type='text/javascript' charset='utf-8' src='settings.js') 
   40|     script(type='text/javascript' charset='utf-8' src='app/editor/static/preview-templates/modular.js') 
   41|     script(type='text/javascript' charset='utf-8' src='app/editor/static/preview-templates/boot.js') 

Invalid indentation, you can use tabs or spaces but not both
   at Lexer.indent (E:\devSoftWare\Creator209\CocosCreator\resources\app.asar\node_modules\jade\lib\lexer.js:790:15)
   at Lexer.next (E:\devSoftWare\Creator209\CocosCreator\resources\app.asar\node_modules\jade\lib\lexer.js:941:15)
   at Lexer.lookahead (E:\devSoftWare\Creator209\CocosCreator\resources\app.asar\node_modules\jade\lib\lexer.js:113:46)
   at Parser.lookahead (E:\devSoftWare\Creator209\CocosCreator\resources\app.asar\node_modules\jade\lib\parser.js:102:23)
   at Parser.peek (E:\devSoftWare\Creator209\CocosCreator\resources\app.asar\node_modules\jade\lib\parser.js:79:17)
   at Parser.tag (E:\devSoftWare\Creator209\CocosCreator\resources\app.asar\node_modules\jade\lib\parser.js:832:30)
   at Parser.parseTag (E:\devSoftWare\Creator209\CocosCreator\resources\app.asar\node_modules\jade\lib\parser.js:759:17)
   at Parser.parseExpr (E:\devSoftWare\Creator209\CocosCreator\resources\app.asar\node_modules\jade\lib\parser.js:211:21)
   at Parser.block (E:\devSoftWare\Creator209\CocosCreator\resources\app.asar\node_modules\jade\lib\parser.js:729:25)
   at Parser.tag (E:\devSoftWare\Creator209\CocosCreator\resources\app.asar\node_modules\jade\lib\parser.js:838:24)

**Comment by potato47** [comment]
那一行要用 tab 键与上面同级的 div 对齐。如果还是不行的话，可以用下面这个直接替换 **index.jade**

```
html
  head
    link(rel='icon' href='app/editor/static/preview-templates/favicon.ico')
    meta(charset='utf-8')
    title=title
    meta(name='viewport' content='width=device-width,user-scalable=no,initial-scale=1, minimum-scale=1,maximum-scale=1')
    meta(name='apple-mobile-web-app-capable' content='yes')
    meta(name='full-screen' content='yes')
    meta(name='screen-orientation' content='portrait')
    meta(name='x5-fullscreen' content='true')
    meta(name='360-fullscreen' content='true')
    
    meta(name='renderer' content='webkit')
    meta(name='force-rendering' content='webkit')
    meta(http-equiv='X-UA-Compatible' content='IE=edge,chrome=1')

    link(rel='stylesheet' href='app/editor/static/preview-templates/style.css')

    block head

  body

    block toolbar
      include ./toolbar.jade

    div.content#content
      div.contentWrap
        div.wrapper#GameDiv
          canvas#GameCanvas

          div#splash
            div.progress-bar.stripes
              span
          div#bulletin
            div.inner#sceneIsEmpty= tip_sceneIsEmpty
    div#recompiling
      span Recompiling scripts, please wait for refresh...
    include ./ccc-devtools/index.html

    script(type='text/javascript' charset='utf-8' src='settings.js')
    script(type='text/javascript' charset='utf-8' src='app/editor/static/preview-templates/modular.js')
    script(type='text/javascript' charset='utf-8' src='app/editor/static/preview-templates/boot.js')
    script(type='text/javascript' charset='utf-8' src='/socket.io/socket.io.js')
    script(type='text/javascript').
        window.__socket_io__ = window.io;
    if enableDebugger
      script(type='text/javascript' charset='utf-8' src='app/node_modules/vconsole/dist/vconsole.min.js')
    script(type='text/javascript' charset='utf-8' src='app/engine/bin/' + cocos2d)

    if enableDebugger
      script(type='text/javascript').
        vConsole = new VConsole();

    if CA
      script(type='text/javascript' charset='utf-8' src='app/editor/static/preview-templates/cocos-analytics/cocosAnalytics.min.js')
      script(type='text/javascript').
        try {
          cocosAnalytics.init({
            appID: !{CA.appID},
            appSecret: !{CA.appSecret},
            channel: !{CA.channel},
            version: !{CA.version}
          });
        }
        catch (e) {}

```

**Comment by zzjfengqing** [comment]
已解决，似乎是用notepad++ 打开后修改保存时 编码问题，插件很好用，十分感谢
