### ISSUE TITLE
啥时候支持下3.6，貌似报错了

### ISSUE THREAD

**Issue by kingkamg** [potato47/ccc-devtools#31]
Error: UI element #error .error-stack doesn't exist.
    at e._queryChecked (http://localhost:7456/preview-app/ui.js:1:7508)
    at new e (http://localhost:7456/preview-app/ui.js:1:1250)
    at http://localhost:7456/preview-app/index.js:1:2404
    at http://localhost:7456/preview-app/index.js:1:1380
    at Object.next (http://localhost:7456/preview-app/index.js:1:1485)
    at c (http://localhost:7456/preview-app/index.js:1:202) {stack: 'Error: UI element #error .error-stack doesn't…://localhost:7456/preview-app/index.js:1:202)', message: 'UI element #error .error-stack doesn't exist.'}

**Comment by potato47** [comment]
已更新
